### PR TITLE
 Fix for EnableBuckets = false on Android #50 

### PR DESCRIPTION
**Pull request by galadril**
Fix for EnableBuckets = false on Android #50 
PS Sorry, but this was developed of the pull request about upgrading the libraries....

so please let me know what you think.

### CODE REVIEW

**Comment by galadril** [comment]
Warning... this pr also contains: https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/pull/58

**Comment by galadril** [comment]
@mierzynskim I've closed the PR with the lib upgrade.
This PR contains the same code (+ a fix for EnableBuckets)

**Comment by galadril** [comment]
@mierzynskim Please assist me on the 'All checks have failed' as i can't see the details of the failure..

**Comment by mierzynskim** [comment]
Hey @galadril! Thanks for your contribution! I'm afraid that we can't updates XF at the moment. The problem is that Xamarin.Forms.GoogleMaps uses old libs and it can lead to errors. Please remove libs update from the PR and I can look at it soon.

**Comment by galadril** [comment]
As requested, ive created a new pull request with the fixes without the lib updates
https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/pull/63

**Pull request closed without merging**
