### PR TITLE
Support for pins collection updates

### LINKED ISSUE #8: ClusterdPins not update on view
When i change item in collection, view not change until i zoom in or zoom out.
Here my code.
`        <clustering:ClusteredMap
            x:Name="Map"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand">
            <clustering:ClusteredMap.Behaviors>
                <bindings:BindingClusteredPinsBehavior Value="{Binding ClusteredPins}" />
            </clustering:ClusteredMap.Behaviors>
        </clustering:ClusteredMap>

On ViewModel

            Device.BeginInvokeOnMainThread(() =>
                {
                    ClusteredPins.Clear();

                    for (var i = 0; i < ClusterItemsCount; i++)
                    {
                        ClusteredPins.Add(new Pin()
                        {
                            Type = PinType.Place,
                            Position = GetRandomLocation(),
                            Label = $"Item {i}",
                            //Icon = BitmapDescriptorFactory.FromBundle("image01.png")
                        });
                    }
                });
`

### PR DESCRIPTION
**Pull request by mierzynskim**
Fixes #8 #17

### CODE REVIEW

**Comment by mierzynskim** [comment]
@kingnguyen1993 @gnout It would be great if you can test this PR and give some feedback if it suits your needs. Thanks in advance!

**Comment by kingnguyen1993** [comment]
@mierzynskim I'm little bussy on project now. I just looked at your changes in code. I think it will work like a charm.

**Comment by gnout** [comment]
@mierzynskim I will take a look at the changes tomorrow morning and I will let you know.

**Comment by gnout** [comment]
@mierzynskim I wasn't able to build the solution. Too many errors. Maybe you can try to download the repository (this specific branch) in a clean machine to try to fix the errors (I was able to build a previous version but not this one!)
Maybe you can upload somewhere the build so I can download it and test it.

**Comment by mierzynskim** [comment]
@gnout It should be fine now.

**Comment by gnout** [comment]
@mierzynskim I can build it now. On comment  is that this branch can only be build in `Debug` configuration. It's fine for now.

**Comment by mierzynskim** [comment]
@gnout Thanks for your time. I released a new version so I hope it works fine for you

**Comment by gnout** [comment]
@mierzynskim Thanks a lot for the update. I will give it and try and let you know.

**Comment by gnout** [comment]
@mierzynskim I think that there must be an error (only in Android). Upon clicking on a pin, I'm changing the icon of the pin from a custom icon to `BitmapDescriptorFactory.DefaultMarker(Color.Red)` and then I'm calling `Cluster();`
The pin disappears instead of changing the icon. Trying to change it back to the custom icon doesn't do anything.
Weird as it sound the "invisible" pin is still on the map but it is not shown! Also by tapping it, the app receive the click event. (I'm just tapping to the place that I know there should be the pin!)
... I hope it make sense.

**Comment by mierzynskim** [comment]
@gnout https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/pull/21 should fix the issue. Nuget package with the fix is available.

**Comment by gnout** [comment]
@mierzynskim Didn't work for me! I just updated to the latest version (0.3.1) and the pin disappears after trying to change the icon.
I tried to change the icon both by calling the `BitmapDescriptorFactory.DefaultMarker(Color.Red)` and the `BitmapDescriptorFactory.FromBundle("..")` but there wasn't any difference.

**Comment by mierzynskim** [comment]
@gnout Yes, you're right. I must have published a nuget without the fix. Sorry for that. 0.3.2 will be published soon and I hope it's fine now

**Comment by gnout** [comment]
@mierzynskim Have you removed the definition of `public IList<Pin> ClusteredPins { get; }` from the definition of `ClusteredMap` class?
Has been replaced with something else?
I'm getting compile errors with this new version!

**Comment by mierzynskim** [comment]
@gnout Yes, it's removed. It wasn't possible to use clustered and not clustered pins at the same time. Here you can check [release notes](https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/blob/master/RELEASE_NOTES.md)

**Pull request merged**
